stages:
  - build
build:linux:
  image: golang:1.9.1
  stage: build
  script:
    - go get github.com/coreos/etcd/clientv3
    - go get github.com/gorilla/handlers
    - go get github.com/nsqio/go-nsq
    - go get github.com/spf13/viper
    - ln -s $PWD $GOPATH/src/MonitorCore
    - cd $GOPATH/src/MonitorCore
    - make build/linux
  artifacts:
    when: on_success
    name: "MonitorCore_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
    - build/
  only:
  - tags

