# Not yet to use
PROJECT_NAME: TEST
# Do check mission each sec.
DURATION: 15

# Link to ETCD
ETCD_HOST: 127.0.0.1
ETCD_PORT: 2379
ETCD_PREFIX: /BBOS/MonitorCore

# Link to NSQ and which TOPIC to send
NSQ_HOST: 127.0.0.1
NSQ_PORT: 4150
NSQ_TOPIC: BBOS_TO_ME

# Listen http port
HTTP_PORT: 9453

# ERROR CODE
#### request method not allowed
ERROR_CODE_HTTP_METHOD_NOT_ALLOWED: 12000001
ERROR_MSG_HTTP_METHOD_NOT_ALLOWED: "Invalid HTTP request method."
#### request param error
ERROR_CODE_UNPROCESSABLE_ENTITY: 120000002
ERROR_MSG_UNPROCESSABLE_ENTITY: "Invalid HTTP request parameter."